namespace MexClub.Application.DTOs.Socios;

public record SocioDto(
    long Id,
    int NumSocio,
    string Codigo,
    long? ReferidoPorSocioId,
    string? ReferidoPorCodigo,
    string Nombre,
    string PrimerApellido,
    string? SegundoApellido,
    string NombreCompleto,
    string TipoDocumento,
    string Documento,
    string? Pais,
    string? Provincia,
    string? Localidad,
    string? Direccion,
    string? CodigoPostal,
    string? Telefono,
    string? Email,
    DateTime? FechaNacimiento,
    DateTime FechaAlta,
    string? FotoUrl,
    string? FotoAnversoDniUrl,
    string? FotoReversoDniUrl,
    bool IsActive,
    short Estrellas,
    int ConsumicionMaximaMensual,
    bool EsTerapeutica,
    bool EsExento,
    bool PagoConTarjeta,
    string? Comentario,
    SocioDetalleDto? Detalle
);

public record SocioDetalleDto(
    DateTime? CuotaFechaProxima,
    decimal ConsumicionDelMes,
    DateTime? FechaUltimaConsumicion,
    DateTime? FechaUltimaAportacion,
    bool ExentoCuota,
    bool DebeCuota,
    decimal Aprovechable
);

public record CreateSocioRequest(
    string Codigo,
    string? ReferidoPor,
    string Nombre,
    string PrimerApellido,
    string? SegundoApellido,
    string TipoDocumento,
    string Documento,
    string? Pais,
    string? Provincia,
    string? Localidad,
    string? Direccion,
    string? CodigoPostal,
    string? Telefono,
    string? Email,
    DateTime? FechaNacimiento,
    short Estrellas,
    int ConsumicionMaximaMensual,
    bool EsTerapeutica,
    bool EsExento,
    bool PagoConTarjeta,
    string? Comentario
);

public record UpdateSocioRequest(
    long Id,
    string Codigo,
    string? ReferidoPor,
    string Nombre,
    string PrimerApellido,
    string? SegundoApellido,
    string TipoDocumento,
    string Documento,
    string? Pais,
    string? Provincia,
    string? Localidad,
    string? Direccion,
    string? CodigoPostal,
    string? Telefono,
    string? Email,
    DateTime? FechaNacimiento,
    short Estrellas,
    int ConsumicionMaximaMensual,
    bool EsTerapeutica,
    bool EsExento,
    bool PagoConTarjeta,
    string? Comentario
);
